apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    info:
      _postman_id: 965aa382-80ff-48e1-814c-9308ac06789d
      name: Swagger-Linting
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    item:
      - name: Validate-Swagger
        request:
          method: GET
          header: []
          url:
            raw: ''
        response: []
    ...
